# Generated by Django 2.1.4 on 2018-12-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
