# Generated by Django 2.1.4 on 2018-12-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='arrival_place_name',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='car_state',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='departure_place_name',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
