# Generated by Django 2.1.4 on 2018-12-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0002_auto_20181212_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='arrival_coord',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='departure_coord',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
